---
- name: Process worker deployment template
  template: 
    src: worker-deployment.yaml.j2
    dest: "{{temp_dir}}/worker-deployment.yaml"

- name: Create maestro worker
  shell: oc apply -f {{temp_dir}}/worker-deployment.yaml -n {{maestro_ns}}

- name: Scale maestro worker to {{test_worker_nodes}} nodes
  shell: oc scale deployment --replicas={{test_worker_nodes}} maestro-worker -n {{maestro_ns}}