---
- name: Process maestro fair increment client template
  template:
      src: fair-increment-client.yaml.j2
      dest: "{{temp_dir}}/fair-increment-client.yaml"

- name: Apply maestro client
  shell: oc apply -f {{temp_dir}}/fair_increment-client.yaml -n {{maestro_ns}}

- name: Ensure maestro {{item.name}} client is running
  shell: oc get pod maestro-client -o jsonpath='{.status.phase}' -n {{maestro_ns}}
  register: result
  until: result.stdout == "Running"
  retries: 20
  delay: 10
  changed_when: False

- name: Check maestro {{item.name}} has finished
  shell: oc get pod maestro-client -o jsonpath='{.status.phase}' -n {{maestro_ns}}
  register: result
  until: result.stdout != "Running"
  retries: 600
  delay: 100
  changed_when: False

- name: Remove current client deployment
  shell: oc delete -f {{temp_dir}}/fair-increment-client.yaml -n {{maestro_ns}}