---
- name: Fetch addressspace standard infra uidd
  shell:  oc get addressspace standard -o yaml -n {{test_ns}} | grep infra-uuid | cut -d ' ' -f6
  register: standard_addressspace
  changed_when: False

- name: Get standard address space uidd
  set_fact:
    standard_uidd: "{{standard_addressspace.stdout}}"

- name: Fetch addressspace brokered infra uidd
  shell:  oc get addressspace brokered -o yaml -n {{test_ns}} | grep infra-uuid | cut -d ' ' -f6
  register: brokered_addressspace
  changed_when: False

- name: Get brokered address space uidd
  set_fact:
    brokered_uidd: "{{brokered_addressspace.stdout}}"

- name: Process test case template
  template:
    src: testcase.yml.j2
    dest: "{{temp_dir}}/testcase-{{item.id}}.yml"
  with_items: "{{ test_configs }}"

- name: Apply test case config map
  shell: oc apply -f {{temp_dir}}/testcase-{{item.id}}.yml -n {{ maestro_ns }}
  with_items: "{{test_configs}}"

- include: execute_tests.yml pkgName="{{item}}"
  with_items: "{{ test_configs }}"
    