apiVersion: user.enmasse.io/v1beta1
kind: MessagingUser
metadata:
  name: standard.user1
spec:
  username: user1
  authentication:
    type: password
    password: cGFzc3dvcmQ= # Base64 encoded
  authorization:
    - addresses: ["small-queue"]
      operations: ["send", "recv"]
